apiVersion: v1
kind: Pod
metadata:
  name: shell2
  labels:
    networking: shell2    
spec:
  containers:
  - name: shell2
    image: busybox
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "10m"
    command:
    - sleep
    args:
    - "999999"