apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp1.2
spec:
  selector:
    matchLabels:
      app: exp1.2
  template:
    metadata:
      labels:
        app: exp1.2
    spec:
      ### security context POD
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      ### 
      containers:
      -  name: busybox
         image: busybox
         ### security context Container
         securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          ### 
         command: ["/bin/sleep", "3650d"]