apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp1.1
spec:
  selector:
    matchLabels:
      app: exp1.1
  template:
    metadata:
      labels:
        app: exp1.1
    spec:
      containers:
      -  name: busybox
         image: busybox
         command: ["/bin/sleep", "3650d"]